Repository human-osaka-game-2018/GameFramework, pull requests merged in 2019-03, with the labels that each got.

#9 RectSizeの機能追加
  GameFramework/RectSize/RectSize.h
Labels: enhancement

#11 RectSizeに既定のコンストラクタを追加
  GameFramework/RectSize/RectSize.h
Labels: enhancement

#25 回転角度のラッパクラスの作成
  GameFramework/GameFramework.vcxproj
  GameFramework/GameFramework.vcxproj.filters
  GameFramework/GameFramework/DirectXParam/DirectXDevice/DirectX9Device.cpp
  GameFramework/GameFramework/DirectXParam/DirectXDevice/DirectX9Device.h
  GameFramework/GameFramework/DirectXParam/DirectXDevice/DirectXDevice.h
  GameFramework/GameFramework/DirectXParam/DirectXGraphicDevice/DirectX9GraphicDevice.cpp
  GameFramework/GameFramework/DirectXParam/DirectXGraphicDevice/DirectX9GraphicDevice.h
  GameFramework/GameFramework/DirectXParam/DirectXGraphicDevice/DirectXGraphicDevice.h
  GameFramework/GameFramework/DirectXParam/DirectXInputDevice/DirectX8InputDevice.cpp
  GameFramework/GameFramework/DirectXParam/DirectXInputDevice/DirectX8InputDevice.h
  GameFramework/GameFramework/DirectXParam/DirectXInputDevice/DirectXInputDevice.h
  GameFramework/GameFramework/GameFrameworkFactory/GameFrameworkFactory.h
  GameFramework/RectSize/RectSize.h
  GameFramework/RotationValue/Degree.cpp
  GameFramework/RotationValue/Degree.h
  GameFramework/RotationValue/Radian.cpp
  GameFramework/RotationValue/Radian.h
  GameFramework/RotationValue/RotationValue.cpp
  GameFramework/RotationValue/RotationValue.h
  GameFramework/Window/Window.cpp
  GameFramework/Window/Window.h
  GameFramework/Window/WindowParam/WindowParam.cpp
  GameFramework/Window/WindowParam/WindowParam.h
Labels: enhancement

#28 DirectXParam関連クラスのリファクタリング
  GameFramework/GameFramework/DirectXParam/DirectXDevice/DirectX9Device.cpp
  GameFramework/GameFramework/DirectXParam/DirectXDevice/DirectX9Device.h
  GameFramework/GameFramework/DirectXParam/DirectXDevice/DirectXDevice.h
  GameFramework/GameFramework/DirectXParam/DirectXGraphicDevice/DirectX9GraphicDevice.cpp
  GameFramework/GameFramework/DirectXParam/DirectXGraphicDevice/DirectX9GraphicDevice.h
  GameFramework/GameFramework/DirectXParam/DirectXGraphicDevice/DirectXGraphicDevice.h
  GameFramework/GameFramework/DirectXParam/DirectXInputDevice/DirectX8InputDevice.cpp
  GameFramework/GameFramework/DirectXParam/DirectXInputDevice/DirectX8InputDevice.h
  GameFramework/GameFramework/DirectXParam/DirectXInputDevice/DirectXInputDevice.h
Labels: bug

#44 プロジェクトの構成の修正
  GameFramework/GameFramework.vcxproj
Labels: bug

#45 Window関連のクラスのリファクタリング
  GameFramework/Window/Window.cpp
  GameFramework/Window/Window.h
  GameFramework/Window/WindowParam/WindowParam.cpp
  GameFramework/Window/WindowParam/WindowParam.h
Labels: enhancement

#47 コメントの修正
  GameFramework/RectSize/RectSize.h
  GameFramework/RotationValue/Degree.cpp
  GameFramework/RotationValue/Degree.h
  GameFramework/RotationValue/Radian.cpp
  GameFramework/RotationValue/Radian.h
  GameFramework/RotationValue/RotationValue.cpp
  GameFramework/RotationValue/RotationValue.h
Labels: correction

#54 Colorクラスにて範囲外アクセス発生
  GameFramework/Color/Color.h
  GameFrameworkTest/ColorTest.cpp
Labels: bug

#55 コメントの修正
  GameFramework/GameFramework/DirectXParam/DirectXDevice/DirectX9Device.h
  GameFramework/GameFramework/DirectXParam/DirectXDevice/DirectXDevice.h
  GameFramework/GameFramework/DirectXParam/DirectXGraphicDevice/DirectX9GraphicDevice.h
  GameFramework/GameFramework/DirectXParam/DirectXGraphicDevice/DirectXGraphicDevice.h
  GameFramework/GameFramework/DirectXParam/DirectXInputDevice/DirectX8InputDevice.h
  GameFramework/GameFramework/DirectXParam/DirectXInputDevice/DirectXInputDevice.h
  GameFramework/GameFramework/GameFrameworkFactory/GameFrameworkFactory.h
  GameFramework/RectSize/RectSize.h
  GameFramework/RotationValue/Degree.h
  GameFramework/RotationValue/RotationValue.h
  GameFramework/Singleton/SingletonHolder/SingletonHolder.h
  GameFramework/Window/Window.h
  GameFramework/Window/WindowParam/WindowParam.h
Labels: correction

#56 アルゴリズム名前空間の作成
  GameFramework/Algorithm/Algorithm.cpp
  GameFramework/Algorithm/Algorithm.h
  GameFramework/GameFramework.vcxproj
Labels: enhancement

#59 テクスチャ座標クラスの作成
  GameFramework/GameFramework.vcxproj
  GameFramework/GameFramework.vcxproj.filters
  GameFramework/TextureUVs/TextureUVs.cpp
  GameFramework/TextureUVs/TextureUVs.h
Labels: enhancement

#61 頂点情報クラスの作成
  GameFramework/GameFramework.vcxproj
  GameFramework/GameFramework/Vertices/DirectX9Vertices.cpp
  GameFramework/GameFramework/Vertices/DirectX9Vertices.h
  GameFramework/GameFramework/Vertices/Vertices.h
Labels: enhancement

#65 描画の準備及び終了処理をするクラスの作成
  GameFramework/GameFramework.vcxproj.filters
  GameFramework/GameFramework/Graphic/Renderer/DirectX9Renderer.cpp
  GameFramework/GameFramework/Graphic/Renderer/DirectX9Renderer.h
  GameFramework/GameFramework/Graphic/Renderer/Renderer.h
Labels: enhancement

#66 色の合成方法設定クラスの作成
  GameFramework/GameFramework.vcxproj
  GameFramework/GameFramework.vcxproj.filters
  GameFramework/GameFramework/Graphic/ColorBlender/ColorBlender.h
  GameFramework/GameFramework/Graphic/ColorBlender/DirectX9ColorBlender.cpp
  GameFramework/GameFramework/Graphic/ColorBlender/DirectX9ColorBlender.h
Labels: enhancement

#67 文字列クラスの作成
  GameFramework/GameFramework.vcxproj
  GameFramework/GameFramework.vcxproj.filters
  GameFramework/GameFramework/Stream/DirectX9Stream.cpp
  GameFramework/GameFramework/Stream/DirectX9Stream.h
  GameFramework/GameFramework/Stream/Stream.h
  GameFramework/tstring/tstring.h
Labels: enhancement

#68 入力クラスの作成
  GameFramework/GameFramework.vcxproj
  GameFramework/GameFramework.vcxproj.filters
  GameFramework/GameFramework/Input/DirectInput/Direct8Input.h
  GameFramework/GameFramework/Input/DirectInput/DirectInput.h
  GameFramework/GameFramework/Input/Input.h
  GameFramework/GameFramework/Input/InputDevice/Direct8InputDevice.h
  GameFramework/GameFramework/Input/InputDevice/DirectX8Keyboard.cpp
  GameFramework/GameFramework/Input/InputDevice/DirectX8Keyboard.h
  GameFramework/GameFramework/Input/InputDevice/DirectX8Mouse.cpp
  GameFramework/GameFramework/Input/InputDevice/DirectX8Mouse.h
  GameFramework/GameFramework/Input/InputDevice/InputDevice.h
Labels: enhancement

#70 フォントクラスの作成
  GameFramework/GameFramework/Graphic/FontManager/Font/DirectX9Font.cpp
  GameFramework/GameFramework/Graphic/FontManager/Font/DirectX9Font.h
  GameFramework/GameFramework/Graphic/FontManager/Font/Font.cpp
  GameFramework/GameFramework/Graphic/FontManager/Font/Font.h
  GameFramework/GameFramework/Graphic/FontManager/FontManager.cpp
  GameFramework/GameFramework/Graphic/FontManager/FontManager.h
Labels: enhancement

#72 リファクタリング
  GameFramework/GameFramework.vcxproj.filters
  GameFramework/GameFramework/TimerManager/TimerManager.h
Labels: enhancement

#74 🐞 Color#operator+ がオーバーフローに対応していない
  GameFramework/Color/Color.h
  GameFrameworkTest/ColorTest.cpp
Labels: bug

#76 🐞 Color#operator+ の計算結果が不正
  GameFramework/Color/Color.h
  GameFrameworkTest/ColorTest.cpp
Labels: bug

#83 命名の修正
  GameFramework/GameFramework/GameFrameworkFactory/GameFrameworkFactory.h
  GameFramework/GameFramework/Graphic/FontManager/FontManager.h
  GameFramework/GameFramework/Graphic/Graphic.h
  GameFramework/GameFramework/Graphic/TextureManager/TextureManager.h
  GameFramework/GameFramework/Input/Input.h
Labels: correction

#87 戻り値を返すように修正
  GameFramework/GameFramework/Graphic/FontManager/FontManager.h
  GameFramework/GameFramework/Graphic/TextureManager/TextureManager.h
Labels: bug

#85 頂点情報クラスの描画関数に引き渡すテクスチャの型を変更
  GameFramework/GameFramework/Vertices/DirectX9Vertices.cpp
  GameFramework/GameFramework/Vertices/DirectX9Vertices.h
  GameFramework/GameFramework/Vertices/Vertices.h
Labels: bug

#89 変数名とtemplate<>のつけ忘れを修正する
  GameFramework/GameFramework/DirectXParam/DirectXParamFactory/DirectXParamFactory.h
  GameFramework/GameFramework/GameFrameworkFactory/GameFrameworkFactory.h
Labels: bug

#93 WindowParamのメンバHWNDの更新処理の追加
  GameFramework/Window/Window.cpp
Labels: bug

#97 IssueとPullRequestのテンプレートを追加
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#95 ライブラリの修正
  GameFramework/GameFramework/DirectXParam/DirectXGraphicDevice/DirectX9GraphicDevice.cpp
  GameFramework/GameFramework/DirectXParam/DirectXGraphicDevice/DirectX9GraphicDevice.h
  GameFramework/GameFramework/DirectXParam/DirectXGraphicDevice/DirectXGraphicDevice.h
  GameFramework/GameFramework/Graphic/FontManager/Font/Font.h
  GameFramework/GameFramework/Graphic/TextureManager/Texture/Texture.h
  GameFramework/GameFramework/Vertices/DirectX9Vertices.cpp
  GameFramework/GameFramework/Vertices/Vertices.h
  GameFramework/Window/Window.cpp
Labels: bug

#101 [issue #100] tstringの実フォルダとフィルタの階層を統一
  GameFramework/GameFramework.vcxproj.filters
Labels: bug

#104 HISTANCEの受け渡し方法の変更
  GameFramework/GameFramework/DirectXParam/DirectXParam.h
  GameFramework/Window/Window.cpp
Labels: correction

#111 GetFont()関数の戻りを返すように修正する
  GameFramework/GameFramework/GameFramework.h
  GameFramework/GameFramework/Graphic/Graphic.h
Labels: bug

#112 [issue #82] 関数名の修正
  GameFramework/GameFramework/Vertices/Vertices.h
Labels: bug

#116 代入演算子を文字列クラスに追加する
  GameFramework/GameFramework/Stream/Stream.h
Labels: enhancement

#118 [issue #82] 関数名の修正
  GameFramework/GameFramework/Vertices/Vertices.h
Labels: correction

#120 関数名の書式の修正
  GameFramework/GameFramework/Vertices/Vertices.cpp
  GameFramework/GameFramework/Vertices/Vertices.h
Labels: correction

#127 [issue #126] Streamクラスの関数の修正
  GameFramework/GameFramework/Stream/Stream.h
Labels: bug, correction

#128 現在のアニメーションのコマ数を取得する関数の追加
  GameFramework/TextureUVs/TextureUVs.h
Labels: enhancement

#135 フォントとテクスチャの開放処理の修正
  GameFramework/GameFramework/GameFramework.h
  GameFramework/GameFramework/Graphic/FontManager/FontManager.h
  GameFramework/GameFramework/Graphic/Graphic.h
  GameFramework/GameFramework/Graphic/TextureManager/TextureManager.h
Labels: bug
